name: gtag_analytics
description: >
  A minimal Google Analytics interop library. Allows triggering page views
  and other events from Dart code.
version: 0.1.7+2
homepage: https://github.com/filiph/gtag_analytics
author: Filip Hracek <filip.hracek@gmail.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  js: ^0.6.1
  meta: ^1.1.2

dev_dependencies:
  test: '>=0.12.0 <2.0.0'
